export const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
export function ema(values,p){if(!values.length)return[];const k=2/(p+1),out=[];let x=values[0];values.forEach((v,i)=>{x=i?v*k+x*(1-k):v;out.push(x)});return out}
export function rsi(values,p=14){if(values.length<=p)return 50;let g=0,l=0;for(let i=1;i<=p;i++){const d=values[i]-values[i-1];g+=Math.max(0,d);l+=Math.max(0,-d)}let ag=g/p,al=l/p;for(let i=p+1;i<values.length;i++){const d=values[i]-values[i-1];ag=(ag*(p-1)+Math.max(0,d))/p;al=(al*(p-1)+Math.max(0,-d))/p}return al===0?100:100-100/(1+ag/al)}
export function trueRanges(c){const out=[c[0]?.high-c[0]?.low||0];for(let i=1;i<c.length;i++)out.push(Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close)));return out}
export function wilders(values,p=14){if(values.length<p)return[];const out=new Array(values.length).fill(null);let x=values.slice(0,p).reduce((a,b)=>a+b,0)/p;out[p-1]=x;for(let i=p;i<values.length;i++){x=(x*(p-1)+values[i])/p;out[i]=x}return out}
export function atr(c,p=14){const a=wilders(trueRanges(c),p);return a.at(-1)||0}
export function adx(c,p=14){if(c.length<p*2)return 0;const tr=trueRanges(c),pd=[0],md=[0];for(let i=1;i<c.length;i++){const up=c[i].high-c[i-1].high,dn=c[i-1].low-c[i].low;pd.push(up>dn&&up>0?up:0);md.push(dn>up&&dn>0?dn:0)}const a=wilders(tr,p),ps=wilders(pd,p),ms=wilders(md,p),dx=new Array(c.length).fill(0);for(let i=0;i<c.length;i++){if(a[i]&&ps[i]!=null&&ms[i]!=null){const plus=100*ps[i]/a[i],minus=100*ms[i]/a[i],sum=plus+minus;dx[i]=sum?100*Math.abs(plus-minus)/sum:0}}return wilders(dx,p).at(-1)||0}
export function macdHist(values){const a=ema(values,12),b=ema(values,26),line=values.map((_,i)=>a[i]-b[i]),sig=ema(line,9);return line.at(-1)-sig.at(-1)}
export function pivots(c,left=2,right=2){const highs=[],lows=[];for(let i=left;i<c.length-right;i++){let hi=true,lo=true;for(let j=i-left;j<=i+right;j++)if(j!==i){if(c[j].high>=c[i].high)hi=false;if(c[j].low<=c[i].low)lo=false}if(hi)highs.push({i,price:c[i].high,ts:c[i].ts});if(lo)lows.push({i,price:c[i].low,ts:c[i].ts})}return{highs,lows}}
export function structure(c){const p=pivots(c),hs=p.highs.slice(-3),ls=p.lows.slice(-3),last=c.at(-1);let state='RANGE',bos='NONE';if(hs.length>=2&&ls.length>=2){const hh=hs.at(-1).price>hs.at(-2).price,hl=ls.at(-1).price>ls.at(-2).price,lh=hs.at(-1).price<hs.at(-2).price,ll=ls.at(-1).price<ls.at(-2).price;if(hh&&hl)state='BULL';if(lh&&ll)state='BEAR'}const h=hs.at(-1)?.price??null,l=ls.at(-1)?.price??null;if(h&&last.close>h)bos='BULL';if(l&&last.close<l)bos='BEAR';return{state,bos,swingHigh:h,swingLow:l,pivots:p}}
