# One Month V12 — GitHub Root Edition

โครงสร้างที่ใช้จริง:

```text
index.html
app.css
app.js
engine.js
indicators.js
market.js
storage.js
xauusd.json
news.json
update-data.mjs
README.md

.github/
  workflows/
    update-data.yml
```

ทุกไฟล์ของเว็บอยู่ root โดยตรง ดังนั้น GitHub Pages อ่านได้ง่ายเหมือนที่เห็นในหน้า repository

ข้อยกเว้นเดียว:
`update-data.yml` ต้องอยู่ `.github/workflows/` เพราะ GitHub Actions ไม่อ่าน workflow ที่วางไว้ root

## Auto Data

Repository Settings → Secrets and variables → Actions → New repository secret

ชื่อ:
`TWELVE_DATA_API_KEY`

จากนั้น Actions → Update XAUUSD data pack → Run workflow

workflow จะรัน `node update-data.mjs` และเขียน:
- `xauusd.json`
- `news.json`

กลับเข้า root ของ repository อัตโนมัติ



# Flat Root Edition

เวอร์ชันนี้ออกแบบให้ทุกไฟล์อยู่ที่ root ของ GitHub repository ได้โดยตรง:

```text
index.html
app.css
app.js
engine.js
indicators.js
market.js
storage.js
xauusd.json
news.json
update-data.mjs
update-data.yml
README.md
```

หมายเหตุสำคัญ:
- เว็บจะอ่าน `app.css`, `app.js`, `xauusd.json`, `news.json` จาก root โดยตรง
- `update-data.mjs` จะเขียน `xauusd.json` และ `news.json` ลง root
- สำหรับ GitHub Actions จริง GitHub ต้องการ workflow อยู่ใน `.github/workflows/`
  ดังนั้นไฟล์ `update-data.yml` ที่อยู่ root เป็นไฟล์ต้นฉบับสำหรับอัปโหลด/เก็บไว้
  ถ้าต้องการให้ Action ทำงานอัตโนมัติ ต้องย้าย/คัดลอกไฟล์นี้ไป `.github/workflows/update-data.yml`

# One Month — Studio V11

Static GitHub Pages app with a separate UI, market-data layer, AI engine, local signal dataset, and GitHub Actions data pack.

## Files
- `index.html` — app shell only
- `assets/css/app.css` — professional mobile UI
- `assets/js/app.js` — plan + UI controller
- `assets/js/market.js` — static pack + Twelve Data + news
- `assets/js/indicators.js` — indicator/math primitives
- `assets/js/engine.js` — multi-timeframe setup engine, risk, lot sizing
- `assets/js/storage.js` — plan compatibility, cache, IndexedDB signal memory
- `data/xauusd.json` — historical pack generated by GitHub Actions
- `data/news.json` — cached gold-impact news pack
- `scripts/update-data.mjs` — action data builder
- `.github/workflows/update-data.yml` — automatic refresh

## GitHub setup
1. Upload the whole project to the repository root.
2. Repository → Settings → Secrets and variables → Actions → New repository secret.
3. Name it `TWELVE_DATA_API_KEY` and paste your Twelve Data key.
4. Actions → `Update XAUUSD data pack` → Run workflow once.
5. Enable GitHub Pages from the repository branch/root.

The scheduled workflow runs 4 times per weekday. The app reads the committed pack first, so opening charts does not spend API credits. Live AI uses the user's API key only when AI is switched ON.

## Own AI dataset
Finished AI signals are stored in IndexedDB in the user's browser. Stats → Export JSON downloads the accumulated dataset. This avoids exposing a write token in a public GitHub Pages app.

For cross-device/shared training data, move the signal store to Supabase/Cloudflare D1 later rather than writing from a public browser directly to GitHub.


## V12 — Pro native chart
- 30–36 candles per mobile screen
- Drag horizontally to pan historical candles
- Pinch to zoom 18–72 bars
- Tap a candle for crosshair + OHLC
- Latest button resets the viewport
- Clean price axis/current-price tag/time axis
- EMA 9/21 + only important swing points
- Entry zone + SL/TP overlays without distorting scale
